/**********************************************
 * Prototype for the typical test modules
 **********************************************/

// ReSharper disable UnusedParameter
// ReSharper disable InconsistentNaming

define(["testFns"], function (testFns) {
    var breeze = testFns.breeze;
    var entityModel = breeze.entityModel;

    // REMOVE what you don't need
    var MetadataStore = entityModel.MetadataStore;
    var EntityManager = entityModel.EntityManager;
    var EntityQuery = entityModel.EntityQuery;
    var EntityKey = entityModel.EntityKey;
    var EntityState = entityModel.EntityState;
    var qop = entityModel.FilterQueryOp;
    var Enum = breeze.core.Enum;

    // CONFIRM that you want to test with Northwind service
    var serviceName = testFns.northwindServiceName,
        metadataStore = new MetadataStore(),
        newEm = testFns.emFactory(serviceName, metadataStore);

    // DELETE and remove from module call if no special metadata setup logic 
    var metadataSetupFn = function () {
        // optional logic to do something with the metadata such as
        // var custType = metadataStore.getEntityType("Customer");
        // custType.autoGeneratedKeyType = AutoGeneratedKeyType.KeyGenerator;
    };

    /*** RENAME THIS MODULE ***/
    module("testsPrototype", testFns.moduleSetupTeardown(newEm, metadataStore, metadataSetupFn));

    // YOUR TESTS HERE (
    // REMEMBER start() in asyncTest calls
    // When expecting a certain number of tests (the 2nd param)
    // remember to count tests in the setup and teardown!

    asyncTest("Passing test", 2, function () {
        ok(true, "This test succeeds");
        start();
    });

    asyncTest("Failing test", 2, function () {
        ok(false, "This test fails");
        start();
    });

    return testFns;
});