setup: &setup
  adapter:  mysql2
  encoding: utf8
  pool:     5
  host:     127.0.0.1
  port:     3306

development:
  database: ccjs_ruby_development
  username: admin
  password: pa$$word
  <<: *setup

test:
  database: ccjs_ruby_test
  username: admin
  password: pa$$word
  <<: *setup

production:
  database: ccjs_ruby_production
  username: admin
  password: pa$$word
  <<: *setup
