package com.breezejs.hib;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.hibernate.Criteria;
import org.hibernate.Session;

import com.breezejs.OdataParameters;
import com.breezejs.QueryResult;
import com.breezejs.save.ContextProvider;
import com.breezejs.save.SaveOptions;
import com.breezejs.save.SaveResult;
import com.breezejs.util.Json;
import com.sun.json.JSONDeserializer;
import com.sun.json.JSONSerializer;

public class DataService {
	
	private static String metadataJson; 

	public String getMetadata() {
		if (metadataJson == null) {
			metadataJson = Json.toJson(StaticSessionFactory.getMetadataMap(), false, false);
		}
		return metadataJson;
	}

	public String queryToJson(Class clazz, String queryString) {
    	OdataParameters op = OdataParameters.parse(queryString);
    	return queryToJson(clazz, op);
	}
	
	public String queryToJson(Class clazz, OdataParameters op) {
//    	op = OdataParameters.parse("http://localhost:7149/breeze/DemoNH/Customers?$top=3&$expand=Orders");
//    	op = OdataParameters.parse("$top=3&$select=Country,PostalCode&$inlinecount=allpages");
    	log(op);

		Session session = StaticSessionFactory.openSession();
		try {
			session.beginTransaction();
	    	
	    	Criteria crit = session.createCriteria(clazz);
	    	
	    	// Here, we could apply filtering to criteria based on e.g. user id...
	    	
	    	// Apply OData parameters to the Criteria
	    	OdataCriteria.applyParameters(crit, op);
	    	log(crit);

	    	String json = queryToJson(crit, op.hasInlineCount());
	    	
			session.getTransaction().commit();
			return json;
		}
    	catch (RuntimeException e) {
    		session.getTransaction().rollback();
    	    throw e; // or display error message
    	}
    	finally {
    		session.close();
    	}    	
	}
	
	public String queryToJson(Criteria crit, boolean inlineCount) {
		List result = crit.list();
		log(result.size());
		log(result);
		
		String json;
		if (inlineCount) {

//	    	Criteria countCrit = session.createCriteria(clazz);
//			OdataCriteria.applyInlineCount(countCrit, op);
			OdataCriteria.applyInlineCount(crit);
			long countResult = (long) crit.uniqueResult();
			log(countResult);
			
			QueryResult qr = new QueryResult(result, countResult);
			json = Json.toJson(qr);
			
		} else {
			json = Json.toJson(result);
		}
		
		log(json);
		return json;
	}
	
	/**
	 * Execute an HQL query and return the results as JSON
	 * @param hqlQuery
	 * @return
	 */
	public String queryToJson(String hqlQuery) {

		Session session = StaticSessionFactory.openSession();
		try {
			session.beginTransaction();
			List result = session.createQuery(hqlQuery).list();
			session.getTransaction().commit();
			return Json.toJson(result);
		}
    	catch (RuntimeException e) {
    		session.getTransaction().rollback();
    	    throw e; // or display error message
    	}
    	finally {
    		session.close();
    	}    	
	}

	public String saveChanges(String source) {
		log(source);
		ContextProvider context = new ContextProvider();
		SaveResult sr = context.saveChanges(source);
		
		String result = Json.toJson(sr);
		log(result);
		
		return result;
	}
	
	
	public void log(Object x) {
    	System.out.println(">>> NorthBreeze: " + x);
	}
	
	/**
	 * For debugging
	 */
    public static void main(String[] args) throws Exception {
    	
    	DataService ds = new DataService();
    	String saveBundle = "{'entities':[{'customerID':'04fa5e78-f2cb-d74d-a7de-083ee17b6ad2','rowVersion':2,'customerID_OLD':'ALFKI','companyName':'Alfreds Futterkiste','contactName':'Maria K. Anders','contactTitle':'Sales Representativ','address':'Obere Str. 57','city':'Berlin','region':'Ost','postalCode':'12209','country':'Germany','phone':'030-0074321','fax':'030-0076545','entityAspect':{'entityTypeName':'Customer:#northwind.model','defaultResourceName':'Customers','entityState':'Modified','originalValuesMap':{'contactTitle':'Sales Representative','rowVersion':1},'autoGeneratedKey':{'propertyName':'customerID','autoGeneratedKeyType':'KeyGenerator'}}}],'saveOptions':{}}";
    	ds.saveChanges(saveBundle);
//    	String meta = ds.getMetadata();
//    	ds.log(meta);
//    	Session session = NorthwindSessionFactory.openSession();
    	
//    	OdataParameters op = OdataParameters.parse("?$top=5&$filter=Country eq 'Brazil'");
//    	op = OdataParameters.parse("http://localhost:7149/breeze/DemoNH/Customers?$top=3&$expand=Orders");
//    	op = OdataParameters.parse("$top=3&$select=Country,PostalCode&$inlinecount=allpages");
//    	log(op);
    	
//    	Criteria crit = session.createCriteria(Customer.class);
//    	OdataCriteria.applyParameters(crit, op);
    	
//    	nb.queryToJson(Customer.class, "?$top=5&$filter=country eq 'Brazil'");
//    	ds.queryToJson(northwind.model.Customer.class, "?$top=5&$filter=country eq 'Brazil'&$inlinecount=allpages");
    	System.exit(0);
    }
    
	
}
