var x = {
    "metadataVersion": "1.0.2",
    "namingConvention": "camelCase",
    "localQueryComparisonOptions": "caseInsensitiveSQL",

    "structuralTypeMap": {
        "Location:#Models.NorthwindIB.EDMX_2012": {
            "shortName": "Location",
            "namespace": "Models.NorthwindIB.EDMX_2012",
            "dataProperties": [
                {
                    "name": "address",
                    "dataType": "String",
                    "maxLength": 60,
                    "validators": [
                        {
                            "maxLength": 60,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "city",
                    "dataType": "String",
                    "maxLength": 15,
                    "validators": [
                        {
                            "maxLength": 15,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "region",
                    "dataType": "String",
                    "maxLength": 15,
                    "validators": [
                        {
                            "maxLength": 15,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "postalCode",
                    "dataType": "String",
                    "maxLength": 10,
                    "validators": [
                        {
                            "maxLength": 10,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "country",
                    "dataType": "String",
                    "maxLength": 15,
                    "validators": [
                        {
                            "maxLength": 15,
                            "validatorName": "maxLength"
                        }
                    ]
                }
            ]
        },
        "Category:#Models.NorthwindIB.EDMX_2012": {
            "shortName": "Category",
            "namespace": "Models.NorthwindIB.EDMX_2012",
            "autoGeneratedKeyType": "Identity",
            "defaultResourceName": "Categories",
            "dataProperties": [
                {
                    "name": "categoryID",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "isPartOfKey": true,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int32"
                        }
                    ]
                },
                {
                    "name": "categoryName",
                    "dataType": "String",
                    "isNullable": false,
                    "defaultValue": "",
                    "maxLength": 15,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "maxLength": 15,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "description",
                    "dataType": "String",
                    "validators": [
                        {
                            "validatorName": "string"
                        }
                    ]
                },
                {
                    "name": "picture",
                    "dataType": "Binary",
                    "validators": [
                        {
                            "validatorName": "none"
                        }
                    ]
                },
                {
                    "name": "rowVersion",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int32"
                        }
                    ]
                }
            ],
            "navigationProperties": [
                {
                    "name": "products",
                    "entityTypeName": "Product:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": false,
                    "associationName": "FK_Product_Category"
                }
            ]
        },
        "Customer:#Models.NorthwindIB.EDMX_2012": {
            "shortName": "Customer",
            "namespace": "Models.NorthwindIB.EDMX_2012",
            "autoGeneratedKeyType": "Identity",
            "defaultResourceName": "Customers",
            "dataProperties": [
                {
                    "name": "customerID",
                    "dataType": "Guid",
                    "isNullable": false,
                    "defaultValue": "00000000-0000-0000-0000-000000000000",
                    "isPartOfKey": true,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "guid"
                        }
                    ]
                },
                {
                    "name": "customerID_OLD",
                    "dataType": "String",
                    "maxLength": 5,
                    "validators": [
                        {
                            "maxLength": 5,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "companyName",
                    "dataType": "String",
                    "isNullable": false,
                    "defaultValue": "",
                    "maxLength": 40,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "maxLength": 40,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "contactName",
                    "dataType": "String",
                    "maxLength": 30,
                    "validators": [
                        {
                            "maxLength": 30,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "contactTitle",
                    "dataType": "String",
                    "maxLength": 30,
                    "validators": [
                        {
                            "maxLength": 30,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "address",
                    "dataType": "String",
                    "maxLength": 60,
                    "validators": [
                        {
                            "maxLength": 60,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "city",
                    "dataType": "String",
                    "maxLength": 15,
                    "validators": [
                        {
                            "maxLength": 15,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "region",
                    "dataType": "String",
                    "maxLength": 15,
                    "validators": [
                        {
                            "maxLength": 15,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "postalCode",
                    "dataType": "String",
                    "maxLength": 10,
                    "validators": [
                        {
                            "maxLength": 10,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "country",
                    "dataType": "String",
                    "maxLength": 15,
                    "validators": [
                        {
                            "maxLength": 15,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "phone",
                    "dataType": "String",
                    "maxLength": 24,
                    "validators": [
                        {
                            "maxLength": 24,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "fax",
                    "dataType": "String",
                    "maxLength": 24,
                    "validators": [
                        {
                            "maxLength": 24,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "rowVersion",
                    "dataType": "Int32",
                    "concurrencyMode": "Fixed",
                    "validators": [
                        {
                            "validatorName": "int32"
                        }
                    ]
                }
            ],
            "navigationProperties": [
                {
                    "name": "orders",
                    "entityTypeName": "Order:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": false,
                    "associationName": "FK_Order_Customer"
                }
            ]
        },
        "Employee:#Models.NorthwindIB.EDMX_2012": {
            "shortName": "Employee",
            "namespace": "Models.NorthwindIB.EDMX_2012",
            "autoGeneratedKeyType": "Identity",
            "defaultResourceName": "Employees",
            "dataProperties": [
                {
                    "name": "employeeID",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "isPartOfKey": true,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int32"
                        }
                    ]
                },
                {
                    "name": "lastName",
                    "dataType": "String",
                    "isNullable": false,
                    "defaultValue": "",
                    "maxLength": 30,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "maxLength": 30,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "firstName",
                    "dataType": "String",
                    "isNullable": false,
                    "defaultValue": "",
                    "maxLength": 30,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "maxLength": 30,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "title",
                    "dataType": "String",
                    "maxLength": 30,
                    "validators": [
                        {
                            "maxLength": 30,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "titleOfCourtesy",
                    "dataType": "String",
                    "maxLength": 25,
                    "validators": [
                        {
                            "maxLength": 25,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "birthDate",
                    "dataType": "DateTime",
                    "validators": [
                        {
                            "validatorName": "date"
                        }
                    ]
                },
                {
                    "name": "hireDate",
                    "dataType": "DateTime",
                    "validators": [
                        {
                            "validatorName": "date"
                        }
                    ]
                },
                {
                    "name": "address",
                    "dataType": "String",
                    "maxLength": 60,
                    "validators": [
                        {
                            "maxLength": 60,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "city",
                    "dataType": "String",
                    "maxLength": 15,
                    "validators": [
                        {
                            "maxLength": 15,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "region",
                    "dataType": "String",
                    "maxLength": 15,
                    "validators": [
                        {
                            "maxLength": 15,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "postalCode",
                    "dataType": "String",
                    "maxLength": 10,
                    "validators": [
                        {
                            "maxLength": 10,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "country",
                    "dataType": "String",
                    "maxLength": 15,
                    "validators": [
                        {
                            "maxLength": 15,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "homePhone",
                    "dataType": "String",
                    "maxLength": 24,
                    "validators": [
                        {
                            "maxLength": 24,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "extension",
                    "dataType": "String",
                    "maxLength": 4,
                    "validators": [
                        {
                            "maxLength": 4,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "photo",
                    "dataType": "Binary",
                    "validators": [
                        {
                            "validatorName": "none"
                        }
                    ]
                },
                {
                    "name": "notes",
                    "dataType": "String",
                    "validators": [
                        {
                            "validatorName": "string"
                        }
                    ]
                },
                {
                    "name": "photoPath",
                    "dataType": "String",
                    "maxLength": 255,
                    "validators": [
                        {
                            "maxLength": 255,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "reportsToEmployeeID",
                    "dataType": "Int32",
                    "validators": [
                        {
                            "validatorName": "int32"
                        }
                    ]
                },
                {
                    "name": "rowVersion",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int32"
                        }
                    ]
                }
            ],
            "navigationProperties": [
                {
                    "name": "directReports",
                    "entityTypeName": "Employee:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": false,
                    "associationName": "FK_Employee_Employee"
                },
                {
                    "name": "manager",
                    "entityTypeName": "Employee:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": true,
                    "associationName": "FK_Employee_Employee",
                    "foreignKeyNames": [
                        "reportsToEmployeeID"
                    ]
                },
                {
                    "name": "employeeTerritories",
                    "entityTypeName": "EmployeeTerritory:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": false,
                    "associationName": "FK_EmployeeTerritory_Employee"
                },
                {
                    "name": "orders",
                    "entityTypeName": "Order:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": false,
                    "associationName": "FK_Order_Employee"
                },
                {
                    "name": "territories",
                    "entityTypeName": "Territory:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": false,
                    "associationName": "EmployeeTerritoryNoPayload"
                }
            ]
        },
        "Order:#Models.NorthwindIB.EDMX_2012": {
            "shortName": "Order",
            "namespace": "Models.NorthwindIB.EDMX_2012",
            "autoGeneratedKeyType": "Identity",
            "defaultResourceName": "Orders",
            "dataProperties": [
                {
                    "name": "orderID",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "isPartOfKey": true,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int32"
                        }
                    ]
                },
                {
                    "name": "customerID",
                    "dataType": "Guid",
                    "validators": [
                        {
                            "validatorName": "guid"
                        }
                    ]
                },
                {
                    "name": "employeeID",
                    "dataType": "Int32",
                    "validators": [
                        {
                            "validatorName": "int32"
                        }
                    ]
                },
                {
                    "name": "orderDate",
                    "dataType": "DateTime",
                    "validators": [
                        {
                            "validatorName": "date"
                        }
                    ]
                },
                {
                    "name": "requiredDate",
                    "dataType": "DateTime",
                    "validators": [
                        {
                            "validatorName": "date"
                        }
                    ]
                },
                {
                    "name": "shippedDate",
                    "dataType": "DateTime",
                    "validators": [
                        {
                            "validatorName": "date"
                        }
                    ]
                },
                {
                    "name": "freight",
                    "dataType": "Decimal",
                    "validators": [
                        {
                            "validatorName": "number"
                        }
                    ]
                },
                {
                    "name": "shipName",
                    "dataType": "String",
                    "maxLength": 40,
                    "validators": [
                        {
                            "maxLength": 40,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "shipAddress",
                    "dataType": "String",
                    "maxLength": 60,
                    "validators": [
                        {
                            "maxLength": 60,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "shipCity",
                    "dataType": "String",
                    "maxLength": 15,
                    "validators": [
                        {
                            "maxLength": 15,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "shipRegion",
                    "dataType": "String",
                    "maxLength": 15,
                    "validators": [
                        {
                            "maxLength": 15,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "shipPostalCode",
                    "dataType": "String",
                    "maxLength": 10,
                    "validators": [
                        {
                            "maxLength": 10,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "shipCountry",
                    "dataType": "String",
                    "maxLength": 15,
                    "validators": [
                        {
                            "maxLength": 15,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "rowVersion",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int32"
                        }
                    ]
                }
            ],
            "navigationProperties": [
                {
                    "name": "customer",
                    "entityTypeName": "Customer:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": true,
                    "associationName": "FK_Order_Customer",
                    "foreignKeyNames": [
                        "customerID"
                    ]
                },
                {
                    "name": "employee",
                    "entityTypeName": "Employee:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": true,
                    "associationName": "FK_Order_Employee",
                    "foreignKeyNames": [
                        "employeeID"
                    ]
                },
                {
                    "name": "internationalOrder",
                    "entityTypeName": "InternationalOrder:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": true,
                    "associationName": "FK_InternationalOrder_Order",
                    "foreignKeyNames": [
                        "orderID"
                    ]
                },
                {
                    "name": "orderDetails",
                    "entityTypeName": "OrderDetail:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": false,
                    "associationName": "FK_OrderDetail_Order"
                }
            ]
        },
        "OrderDetail:#Models.NorthwindIB.EDMX_2012": {
            "shortName": "OrderDetail",
            "namespace": "Models.NorthwindIB.EDMX_2012",
            "autoGeneratedKeyType": "None",
            "defaultResourceName": "OrderDetails",
            "dataProperties": [
                {
                    "name": "orderID",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "isPartOfKey": true,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int32"
                        }
                    ]
                },
                {
                    "name": "productID",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "isPartOfKey": true,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int32"
                        }
                    ]
                },
                {
                    "name": "unitPrice",
                    "dataType": "Decimal",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "number"
                        }
                    ]
                },
                {
                    "name": "quantity",
                    "dataType": "Int16",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int16"
                        }
                    ]
                },
                {
                    "name": "discount",
                    "dataType": "Single",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "number"
                        }
                    ]
                },
                {
                    "name": "rowVersion",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int32"
                        }
                    ]
                }
            ],
            "navigationProperties": [
                {
                    "name": "order",
                    "entityTypeName": "Order:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": true,
                    "associationName": "FK_OrderDetail_Order",
                    "foreignKeyNames": [
                        "orderID"
                    ]
                },
                {
                    "name": "product",
                    "entityTypeName": "Product:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": true,
                    "associationName": "FK_OrderDetail_Product",
                    "foreignKeyNames": [
                        "productID"
                    ]
                }
            ]
        },
        "Product:#Models.NorthwindIB.EDMX_2012": {
            "shortName": "Product",
            "namespace": "Models.NorthwindIB.EDMX_2012",
            "autoGeneratedKeyType": "Identity",
            "defaultResourceName": "Products",
            "dataProperties": [
                {
                    "name": "productID",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "isPartOfKey": true,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int32"
                        }
                    ]
                },
                {
                    "name": "productName",
                    "dataType": "String",
                    "isNullable": false,
                    "defaultValue": "",
                    "maxLength": 40,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "maxLength": 40,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "supplierID",
                    "dataType": "Int32",
                    "validators": [
                        {
                            "validatorName": "int32"
                        }
                    ]
                },
                {
                    "name": "categoryID",
                    "dataType": "Int32",
                    "validators": [
                        {
                            "validatorName": "int32"
                        }
                    ]
                },
                {
                    "name": "quantityPerUnit",
                    "dataType": "String",
                    "maxLength": 20,
                    "validators": [
                        {
                            "maxLength": 20,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "unitPrice",
                    "dataType": "Decimal",
                    "validators": [
                        {
                            "validatorName": "number"
                        }
                    ]
                },
                {
                    "name": "unitsInStock",
                    "dataType": "Int16",
                    "validators": [
                        {
                            "validatorName": "int16"
                        }
                    ]
                },
                {
                    "name": "unitsOnOrder",
                    "dataType": "Int16",
                    "validators": [
                        {
                            "validatorName": "int16"
                        }
                    ]
                },
                {
                    "name": "reorderLevel",
                    "dataType": "Int16",
                    "validators": [
                        {
                            "validatorName": "int16"
                        }
                    ]
                },
                {
                    "name": "isDiscontinued",
                    "dataType": "Boolean",
                    "isNullable": false,
                    "defaultValue": false,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "bool"
                        }
                    ]
                },
                {
                    "name": "discontinuedDate",
                    "dataType": "DateTime",
                    "validators": [
                        {
                            "validatorName": "date"
                        }
                    ]
                },
                {
                    "name": "rowVersion",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int32"
                        }
                    ]
                }
            ],
            "navigationProperties": [
                {
                    "name": "category",
                    "entityTypeName": "Category:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": true,
                    "associationName": "FK_Product_Category",
                    "foreignKeyNames": [
                        "categoryID"
                    ]
                },
                {
                    "name": "supplier",
                    "entityTypeName": "Supplier:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": true,
                    "associationName": "FK_Product_Supplier",
                    "foreignKeyNames": [
                        "supplierID"
                    ]
                }
            ]
        },
        "Supplier:#Models.NorthwindIB.EDMX_2012": {
            "shortName": "Supplier",
            "namespace": "Models.NorthwindIB.EDMX_2012",
            "autoGeneratedKeyType": "Identity",
            "defaultResourceName": "Suppliers",
            "dataProperties": [
                {
                    "name": "supplierID",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "isPartOfKey": true,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int32"
                        }
                    ]
                },
                {
                    "name": "companyName",
                    "dataType": "String",
                    "isNullable": false,
                    "defaultValue": "",
                    "maxLength": 40,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "maxLength": 40,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "contactName",
                    "dataType": "String",
                    "maxLength": 30,
                    "validators": [
                        {
                            "maxLength": 30,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "contactTitle",
                    "dataType": "String",
                    "maxLength": 30,
                    "validators": [
                        {
                            "maxLength": 30,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "phone",
                    "dataType": "String",
                    "maxLength": 24,
                    "validators": [
                        {
                            "maxLength": 24,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "fax",
                    "dataType": "String",
                    "maxLength": 24,
                    "validators": [
                        {
                            "maxLength": 24,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "homePage",
                    "dataType": "String",
                    "validators": [
                        {
                            "validatorName": "string"
                        }
                    ]
                },
                {
                    "name": "rowVersion",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int32"
                        }
                    ]
                },
                {
                    "name": "location",
                    "dataType": {
                        "shortName": "Location",
                        "namespace": "Models.NorthwindIB.EDMX_2012",
                        "dataProperties": [
                            {
                                "name": "address",
                                "dataType": "String",
                                "maxLength": 60,
                                "validators": [
                                    {
                                        "maxLength": 60,
                                        "validatorName": "maxLength"
                                    }
                                ]
                            },
                            {
                                "name": "city",
                                "dataType": "String",
                                "maxLength": 15,
                                "validators": [
                                    {
                                        "maxLength": 15,
                                        "validatorName": "maxLength"
                                    }
                                ]
                            },
                            {
                                "name": "region",
                                "dataType": "String",
                                "maxLength": 15,
                                "validators": [
                                    {
                                        "maxLength": 15,
                                        "validatorName": "maxLength"
                                    }
                                ]
                            },
                            {
                                "name": "postalCode",
                                "dataType": "String",
                                "maxLength": 10,
                                "validators": [
                                    {
                                        "maxLength": 10,
                                        "validatorName": "maxLength"
                                    }
                                ]
                            },
                            {
                                "name": "country",
                                "dataType": "String",
                                "maxLength": 15,
                                "validators": [
                                    {
                                        "maxLength": 15,
                                        "validatorName": "maxLength"
                                    }
                                ]
                            }
                        ]
                    },
                    "complexTypeName": "Location:#Models.NorthwindIB.EDMX_2012",
                    "isNullable": false,
                    "validators": [
                        {
                            "validatorName": "required"
                        }
                    ]
                }
            ],
            "navigationProperties": [
                {
                    "name": "products",
                    "entityTypeName": "Product:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": false,
                    "associationName": "FK_Product_Supplier"
                }
            ]
        },

    },
    "resourceEntityTypeMap": {
        "Categories": "Category:#Models.NorthwindIB.EDMX_2012",
        "Customers": "Customer:#Models.NorthwindIB.EDMX_2012",
        "Employees": "Employee:#Models.NorthwindIB.EDMX_2012",
        "Orders": "Order:#Models.NorthwindIB.EDMX_2012",
        "OrderDetails": "OrderDetail:#Models.NorthwindIB.EDMX_2012",
        "Products": "Product:#Models.NorthwindIB.EDMX_2012",
        "Suppliers": "Supplier:#Models.NorthwindIB.EDMX_2012",
    },

}