var x = {
    "structuralTypeMap": {
        "Location:#Models.NorthwindIB.EDMX_2012": {
            "shortName": "Location",
            "namespace": "Models.NorthwindIB.EDMX_2012",
            "dataProperties": [
                {
                    "nameOnServer": "Address",
                    "dataType": "String",
                    "maxLength": 60,
                    "validators": [
                        {
                            "maxLength": 60,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "City",
                    "dataType": "String",
                    "maxLength": 15,
                    "validators": [
                        {
                            "maxLength": 15,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "Region",
                    "dataType": "String",
                    "maxLength": 15,
                    "validators": [
                        {
                            "maxLength": 15,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "PostalCode",
                    "dataType": "String",
                    "maxLength": 10,
                    "validators": [
                        {
                            "maxLength": 10,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "Country",
                    "dataType": "String",
                    "maxLength": 15,
                    "validators": [
                        {
                            "maxLength": 15,
                            "validatorName": "maxLength"
                        }
                    ]
                }
            ]
        },
        "Customer:#Models.NorthwindIB.EDMX_2012": {
            "shortName": "Customer",
            "namespace": "Models.NorthwindIB.EDMX_2012",
            "autoGeneratedKeyType": "Identity",
            "defaultResourceName": "Customers",
            "dataProperties": [
                {
                    "nameOnServer": "CustomerID",
                    "dataType": "Guid",
                    "isNullable": false,
                    "defaultValue": "00000000-0000-0000-0000-000000000000",
                    "isPartOfKey": true,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "guid"
                        }
                    ]
                },
                {
                    "nameOnServer": "CustomerID_OLD",
                    "dataType": "String",
                    "isNullable": true,
                    "defaultValue": null,
                    "maxLength": 5,
                    "validators": [
                        {
                            "maxLength": 5,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "CompanyName",
                    "dataType": "String",
                    "isNullable": false,
                    "defaultValue": "",
                    "maxLength": 40,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "maxLength": 40,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "ContactName",
                    "dataType": "String",
                    "defaultValue": null,
                    "maxLength": 30,
                    "validators": [
                        {
                            "maxLength": 30,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "ContactTitle",
                    "dataType": "String",
                    "defaultValue": null,
                    "maxLength": 30,
                    "validators": [
                        {
                            "maxLength": 30,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "Address",
                    "dataType": "String",
                    "defaultValue": null,
                    "maxLength": 60,
                    "validators": [
                        {
                            "maxLength": 60,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "City",
                    "dataType": "String",
                    "defaultValue": null,
                    "maxLength": 15,
                    "validators": [
                        {
                            "maxLength": 15,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "Region",
                    "dataType": "String",
                    "maxLength": 15,
                    "validators": [
                        {
                            "maxLength": 15,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "PostalCode",
                    "dataType": "String",
                    "maxLength": 10,
                    "validators": [
                        {
                            "maxLength": 10,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "Country",
                    "dataType": "String",
                    "maxLength": 15,
                    "validators": [
                        {
                            "maxLength": 15,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "Phone",
                    "dataType": "String",
                    "maxLength": 24,
                    "validators": [
                        {
                            "maxLength": 24,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "Fax",
                    "dataType": "String",
                    "maxLength": 24,
                    "fixedLength": false,
                    "validators": [
                        {
                            "maxLength": 24,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "RowVersion",
                    "dataType": "Int32",
                    "concurrencyMode": "Fixed",
                    "maxLength": null,
                    "validators": [
                        {
                            "validatorName": "int32"
                        }
                    ]
                }
            ],
            "navigationProperties": [
                {
                    "nameOnServer": "Orders",
                    "entityTypeName": "Order:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": false,
                    "associationName": "FK_Order_Customer"
                }
            ]
        },
        "Employee:#Models.NorthwindIB.EDMX_2012": {
            "shortName": "Employee",
            "namespace": "Models.NorthwindIB.EDMX_2012",
            "autoGeneratedKeyType": "Identity",
            "defaultResourceName": "Employees",
            "dataProperties": [
                {
                    "nameOnServer": "EmployeeID",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int32"
                        }
                    ]
                },
                {
                    "nameOnServer": "LastName",
                    "dataType": "String",
                    "maxLength": 30,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "maxLength": 30,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "FirstName",
                    "dataType": "String",
                    "maxLength": 30,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "maxLength": 30,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "Title",
                    "dataType": "String",
                    "maxLength": 30,
                    "validators": [
                        {
                            "maxLength": 30,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "TitleOfCourtesy",
                    "dataType": "String",
                    "maxLength": 25,
                    "validators": [
                        {
                            "maxLength": 25,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "BirthDate",
                    "dataType": "DateTime",
                    "validators": [
                        {
                            "validatorName": "date"
                        }
                    ]
                },
                {
                    "nameOnServer": "HireDate",
                    "dataType": "DateTime",
                    "validators": [
                        {
                            "validatorName": "date"
                        }
                    ]
                },
                {
                    "nameOnServer": "Address",
                    "dataType": "String",
                    "maxLength": 60,
                    "validators": [
                        {
                            "maxLength": 60,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "City",
                    "dataType": "String",
                    "maxLength": 15,
                    "validators": [
                        {
                            "maxLength": 15,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "Region",
                    "dataType": "String",
                    "maxLength": 15,
                    "validators": [
                        {
                            "maxLength": 15,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "PostalCode",
                    "dataType": "String",
                    "maxLength": 10,
                    "validators": [
                        {
                            "maxLength": 10,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "Country",
                    "dataType": "String",
                    "maxLength": 15,
                    "validators": [
                        {
                            "maxLength": 15,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "HomePhone",
                    "dataType": "String",
                    "maxLength": 24,
                    "validators": [
                        {
                            "maxLength": 24,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "Extension",
                    "dataType": "String",
                    "maxLength": 4,
                    "validators": [
                        {
                            "maxLength": 4,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "Photo",
                    "dataType": "Binary",
                    "validators": [
                        {
                            "validatorName": "none"
                        }
                    ]
                },
                {
                    "nameOnServer": "Notes",
                    "dataType": "String",
                    "validators": [
                        {
                            "validatorName": "string"
                        }
                    ]
                },
                {
                    "nameOnServer": "PhotoPath",
                    "dataType": "String",
                    "maxLength": 255,
                    "validators": [
                        {
                            "maxLength": 255,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "ReportsToEmployeeID",
                    "dataType": "Int32",
                    "validators": [
                        {
                            "validatorName": "int32"
                        }
                    ]
                },
                {
                    "nameOnServer": "RowVersion",
                    "dataType": "Int32",
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int32"
                        }
                    ]
                }
            ],
            "navigationProperties": [
                {
                    "nameOnServer": "DirectReports",
                    "entityTypeName": "Employee:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": false,
                    "associationName": "FK_Employee_Employee"
                },
                {
                    "nameOnServer": "Manager",
                    "entityTypeName": "Employee:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": true,
                    "associationName": "FK_Employee_Employee",
                    "foreignKeyNamesOnServer": [
                        "ReportsToEmployeeID"
                    ]
                },
                {
                    "nameOnServer": "Orders",
                    "entityTypeName": "Order:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": false,
                    "associationName": "FK_Order_Employee"
                }
            ]
        },
        "Order:#Models.NorthwindIB.EDMX_2012": {
            "shortName": "Order",
            "namespace": "Models.NorthwindIB.EDMX_2012",
            "autoGeneratedKeyType": "Identity",
            "defaultResourceName": "Orders",
            "dataProperties": [
                {
                    "nameOnServer": "OrderID",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int32"
                        }
                    ]
                },
                {
                    "nameOnServer": "CustomerID",
                    "dataType": "Guid",
                    "validators": [
                        {
                            "validatorName": "guid"
                        }
                    ]
                },
                {
                    "nameOnServer": "EmployeeID",
                    "dataType": "Int32",
                    "validators": [
                        {
                            "validatorName": "int32"
                        }
                    ]
                },
                {
                    "nameOnServer": "OrderDate",
                    "dataType": "DateTime",
                    "validators": [
                        {
                            "validatorName": "date"
                        }
                    ]
                },
                {
                    "nameOnServer": "RequiredDate",
                    "dataType": "DateTime",
                    "validators": [
                        {
                            "validatorName": "date"
                        }
                    ]
                },
                {
                    "nameOnServer": "ShippedDate",
                    "dataType": "DateTime",
                    "validators": [
                        {
                            "validatorName": "date"
                        }
                    ]
                },
                {
                    "nameOnServer": "Freight",
                    "dataType": "Decimal",
                    "validators": [
                        {
                            "validatorName": "number"
                        }
                    ]
                },
                {
                    "nameOnServer": "ShipName",
                    "dataType": "String",
                    "maxLength": 40,
                    "validators": [
                        {
                            "maxLength": 40,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "ShipAddress",
                    "dataType": "String",
                    "maxLength": 60,
                    "validators": [
                        {
                            "maxLength": 60,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "ShipCity",
                    "dataType": "String",
                    "maxLength": 15,
                    "validators": [
                        {
                            "maxLength": 15,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "ShipRegion",
                    "dataType": "String",
                    "maxLength": 15,
                    "validators": [
                        {
                            "maxLength": 15,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "ShipPostalCode",
                    "dataType": "String",
                    "maxLength": 10,
                    "validators": [
                        {
                            "maxLength": 10,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "ShipCountry",
                    "dataType": "String",
                    "maxLength": 15,
                    "validators": [
                        {
                            "maxLength": 15,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "RowVersion",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int32"
                        }
                    ]
                }
            ],
            "navigationProperties": [
                {
                    "nameOnServer": "Customer",
                    "entityTypeName": "Customer:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": true,
                    "associationName": "FK_Order_Customer",
                    "foreignKeyNamesOnServer": [
                        "CustomerID"
                    ]
                },
                {
                    "nameOnServer": "Employee",
                    "entityTypeName": "Employee:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": true,
                    "associationName": "FK_Order_Employee",
                    "foreignKeyNamesOnServer": [
                        "EmployeeID"
                    ]
                },
                {
                    "nameOnServer": "OrderDetails",
                    "entityTypeName": "OrderDetail:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": false,
                    "associationName": "FK_OrderDetail_Order"
                }
            ]
        },
        "OrderDetail:#Models.NorthwindIB.EDMX_2012": {
            "shortName": "OrderDetail",
            "namespace": "Models.NorthwindIB.EDMX_2012",
            "autoGeneratedKeyType": "None",
            "defaultResourceName": "OrderDetails",
            "dataProperties": [
                {
                    "nameOnServer": "OrderID",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int32"
                        }
                    ]
                },
                {
                    "nameOnServer": "ProductID",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int32"
                        }
                    ]
                },
                {
                    "nameOnServer": "UnitPrice",
                    "dataType": "Decimal",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "number"
                        }
                    ]
                },
                {
                    "nameOnServer": "Quantity",
                    "dataType": "Int16",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int16"
                        }
                    ]
                },
                {
                    "nameOnServer": "Discount",
                    "dataType": "Single",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "number"
                        }
                    ]
                },
                {
                    "nameOnServer": "RowVersion",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int32"
                        }
                    ]
                }
            ],
            "navigationProperties": [
                {
                    "nameOnServer": "Order",
                    "entityTypeName": "Order:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": true,
                    "associationName": "FK_OrderDetail_Order",
                    "foreignKeyNamesOnServer": [
                        "OrderID"
                    ]
                },
                {
                    "nameOnServer": "Product",
                    "entityTypeName": "Product:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": true,
                    "associationName": "FK_OrderDetail_Product",
                    "foreignKeyNamesOnServer": [
                        "ProductID"
                    ]
                }
            ]
        },
        "Product:#Models.NorthwindIB.EDMX_2012": {
            "shortName": "Product",
            "namespace": "Models.NorthwindIB.EDMX_2012",
            "autoGeneratedKeyType": "Identity",
            "defaultResourceName": "Products",
            "dataProperties": [
                {
                    "nameOnServer": "ProductID",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int32"
                        }
                    ]
                },
                {
                    "nameOnServer": "ProductName",
                    "dataType": "String",
                    "isNullable": false,
                    "defaultValue": "",
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "maxLength": 40,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "SupplierID",
                    "dataType": "Int32",
                    "validators": [
                        {
                            "validatorName": "int32"
                        }
                    ]
                },
                {
                    "name": "categoryID",
                    "nameOnServer": "CategoryID",
                    "dataType": "Int32",
                    "validators": [
                        {
                            "validatorName": "int32"
                        }
                    ]
                },
                {
                    "name": "quantityPerUnit",
                    "nameOnServer": "QuantityPerUnit",
                    "dataType": "String",
                    "maxLength": 20,
                    "validators": [
                        {
                            "maxLength": 20,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "unitPrice",
                    "nameOnServer": "UnitPrice",
                    "dataType": "Decimal",
                    "validators": [
                        {
                            "validatorName": "number"
                        }
                    ]
                },
                {
                    "name": "unitsInStock",
                    "nameOnServer": "UnitsInStock",
                    "dataType": "Int16",
                    "validators": [
                        {
                            "validatorName": "int16"
                        }
                    ]
                },
                {
                    "name": "unitsOnOrder",
                    "nameOnServer": "UnitsOnOrder",
                    "dataType": "Int16",
                    "validators": [
                        {
                            "validatorName": "int16"
                        }
                    ]
                },
                {
                    "name": "reorderLevel",
                    "nameOnServer": "ReorderLevel",
                    "dataType": "Int16",
                    "validators": [
                        {
                            "validatorName": "int16"
                        }
                    ]
                },
                {
                    "name": "isDiscontinued",
                    "nameOnServer": "Discontinued",
                    "dataType": "Boolean",
                    "isNullable": false,
                    "defaultValue": false,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "bool"
                        }
                    ]
                },
                {
                    "name": "discontinuedDate",
                    "nameOnServer": "DiscontinuedDate",
                    "dataType": "DateTime",
                    "validators": [
                        {
                            "validatorName": "date"
                        }
                    ]
                },
                {
                    "name": "rowVersion",
                    "nameOnServer": "RowVersion",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int32"
                        }
                    ]
                }
            ],
            "navigationProperties": [
                {
                    "nameOnServer": "Category",
                    "entityTypeName": "Category:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": true,
                    "associationName": "FK_Product_Category",
                    "foreignKeyNamesOnServer": [
                        "CategoryID"
                    ]
                },
                {
                    "nameOnServer": "Supplier",
                    "entityTypeName": "Supplier:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": true,
                    "associationName": "FK_Product_Supplier",
                    "foreignKeyNamesOnServer": [
                        "SupplierID"
                    ]
                }
            ]
        },
        "Supplier:#Models.NorthwindIB.EDMX_2012": {
            "shortName": "Supplier",
            "namespace": "Models.NorthwindIB.EDMX_2012",
            "autoGeneratedKeyType": "Identity",
            "defaultResourceName": "Suppliers",
            "dataProperties": [
                {
                    "nameOnServer": "SupplierID",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int32"
                        }
                    ]
                },
                {
                    "nameOnServer": "CompanyName",
                    "dataType": "String",
                    "isNullable": false,
                    "defaultValue": "",
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "maxLength": 40,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "ContactName",
                    "dataType": "String",
                    "maxLength": 30,
                    "validators": [
                        {
                            "maxLength": 30,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "ContactTitle",
                    "dataType": "String",
                    "maxLength": 30,
                    "validators": [
                        {
                            "maxLength": 30,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "Phone",
                    "dataType": "String",
                    "maxLength": 24,
                    "validators": [
                        {
                            "maxLength": 24,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "nameOnServer": "Fax",
                    "dataType": "String",
                    "maxLength": 24,
                    "validators": [
                        {
                            "maxLength": 24,
                            "validatorName": "maxLength"
                        }
                    ]
                },
                {
                    "name": "homePage",
                    "nameOnServer": "HomePage",
                    "dataType": "String",
                    "validators": [
                        {
                            "validatorName": "string"
                        }
                    ]
                },
                {
                    "nameOnServer": "RowVersion",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                        {
                            "validatorName": "required"
                        },
                        {
                            "validatorName": "int32"
                        }
                    ]
                },
                {
                    "nameOnServer": "Location",
                    "complexTypeName": "Location:#Models.NorthwindIB.EDMX_2012",
                    "validators": [
                        {
                            "validatorName": "required"
                        }
                    ]
                }
            ],
            "navigationProperties": [
                {
                    "nameOnServer": "Products",
                    "entityTypeName": "Product:#Models.NorthwindIB.EDMX_2012",
                    "isScalar": false,
                    "associationName": "FK_Product_Supplier"
                }
            ]
        },
    },
    "resourceEntityTypeMap": {
        "Customers": "Customer:#Models.NorthwindIB.EDMX_2012",
        "Employees": "Employee:#Models.NorthwindIB.EDMX_2012",
        "Orders": "Order:#Models.NorthwindIB.EDMX_2012",
        "OrderDetails": "OrderDetail:#Models.NorthwindIB.EDMX_2012",
        "Products": "Product:#Models.NorthwindIB.EDMX_2012",
        "Suppliers": "Supplier:#Models.NorthwindIB.EDMX_2012",

    }
};