//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.NorthwindIB.Oracle
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NorthwindIBContext_EDMX_Oracle : DbContext
    {
        public NorthwindIBContext_EDMX_Oracle()
        : base("name=NorthwindIBContext_EDMX_Oracle")
        {
        }
    
        public NorthwindIBContext_EDMX_Oracle(DbConnection connection) : base(connection, false) {}

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Categories { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<EmployeeTerritory> EmployeeTerritories { get; set; }
        public DbSet<Geospatial> Geospatials { get; set; }
        public DbSet<InternationalOrder> InternationalOrders { get; set; }
        public DbSet<NextId> NextIds1 { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }
        public DbSet<PreviousEmployee> PreviousEmployees { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Region> Regions { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<Territory> Territories { get; set; }
        public DbSet<TimeGroup> TimeGroups { get; set; }
        public DbSet<TimeLimit> TimeLimits { get; set; }
        public DbSet<UnusualDate> UnusualDates { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
    }
}
