//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.NorthwindIB.EDMX_2012
{
    using System;
    using System.Collections.Generic;
    
    public partial class NextId
    {
        public string Name { get; set; }
        public long NextId1 { get; set; }
    }
}
