YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "AutoGeneratedKeyType",
        "DataProperty",
        "DataType",
        "EntityAction",
        "EntityAspect",
        "EntityKey",
        "EntityManager",
        "EntityQuery",
        "EntityState",
        "EntityType",
        "Enum",
        "EnumSymbol",
        "Event",
        "FetchStrategy",
        "FilterQueryOp",
        "MergeStrategy",
        "MetadataStore",
        "NamingConvention",
        "NavigationProperty",
        "Predicate",
        "QueryOptions",
        "SaveOptions",
        "ValidationError",
        "ValidationOptions",
        "Validator",
        "[relation Array]",
        "config",
        "~entityTracking-interface",
        "~keyGenerator-interface"
    ],
    "modules": [
        "core",
        "entityModel"
    ],
    "allModules": [
        {
            "displayName": "core",
            "name": "core",
            "description": "Utility types and functions of generally global applicability."
        },
        {
            "displayName": "entityModel",
            "name": "entityModel",
            "description": "The entityModel namespace."
        }
    ]
} };
});