(function (factory) {
    if (breeze) {
        factory(breeze);
    } else if (typeof require === "function" && typeof exports === "object" && typeof module === "object") {
        // CommonJS or Node: hard-coded dependency on "breeze"
        factory(require("breeze"));
    } else if (typeof define === "function" && define["amd"] && !breeze) {
        // AMD anonymous module with hard-coded dependency on "breeze"
        define(["breeze"], factory);
    }
}(function(breeze) {
    
    var core = breeze.core;
 
    var MetadataStore = breeze.MetadataStore;
    var JsonResultsAdapter = breeze.JsonResultsAdapter;
    
    var OData;
    
    var ctor = function () {
        this.name = "OData";
    };

    ctor.prototype.initialize = function () {
        OData = core.requireLib("OData", "Needed to support remote OData services");
        OData.jsonHandler.recognizeDates = true;
    };
    
    
    ctor.prototype.executeQuery = function (mappingContext) {
    
        var deferred = Q.defer();

        OData.read(mappingContext.url,
            function (data, response) {
                return deferred.resolve({ results: data.results, inlineCount: data.__count });
            },
            function (error) {
                return deferred.reject(createError(error, mappingContext.url));
            }
        );
        return deferred.promise;
    };
    

    ctor.prototype.fetchMetadata = function (metadataStore, dataService) {

        var deferred = Q.defer();

        var serviceName = dataService.serviceName;
        var url = dataService.makeUrl('$metadata');
        
        OData.read(url,
            function (data) {
                // data.dataServices.schema is an array of schemas. with properties of 
                // entityContainer[], association[], entityType[], and namespace.
                if (!data || !data.dataServices) {
                    var error = new Error("Metadata query failed for: " + url);
                    return deferred.reject(error);
                }
                var csdlMetadata = data.dataServices;

                // might have been fetched by another query
                if (!metadataStore.hasMetadataFor(serviceName)) {
                    try {
                        metadataStore.importMetadata(csdlMetadata);
                    } catch(e) {
                        return deferred.reject(new Error("Metadata query failed for " + url + "; Unable to process returned metadata: " + e.message));
                    }

                    metadataStore.addDataService(dataService);
                }

                return deferred.resolve(csdlMetadata);

            }, function (error) {
                var err = createError(error, url);
                err.message = "Metadata query failed for: " + url + "; " + (err.message || "");
                return deferred.reject(err);
            },
            OData.metadataHandler
        );

        return deferred.promise;

    };

    ctor.prototype.saveChanges = function (saveContext, saveBundle) {

        var deferred = Q.defer();

        var helper = saveContext.entityManager.helper;
        var url = saveContext.dataService.makeUrl("$batch");
        
        var requestData = createChangeRequests(saveContext, saveBundle);
        var tempKeys = saveContext.tempKeys;
        var contentKeys = saveContext.contentKeys;
        OData.request({
            headers : { "DataServiceVersion": "2.0" } ,
            requestUri: url,
            method: "POST",
            data: requestData
        }, function (data, response) {
            var entities = [];
            var keyMappings = [];
            var saveResult = { entities: entities, keyMappings: keyMappings };
            data.__batchResponses.forEach(function(br) {
                br.__changeResponses.forEach(function (cr) {
                    var response = cr.response || cr;
                    var statusCode = response.statusCode;
                    if ((!statusCode) || statusCode >= 400) {
                        return deferred.reject(createError(cr, url));
                    }
                    
                    var contentId = cr.headers["Content-ID"];
                    
                    var rawEntity = cr.data;
                    if (rawEntity) {
                        var tempKey = tempKeys[contentId];
                        if (tempKey) {
                            var entityType = tempKey.entityType;
                            if (entityType.autoGeneratedKeyType !== AutoGeneratedKeyType.None) {
                                var tempValue = tempKey.values[0];
                                var realKey = helper.getEntityKeyFromRawEntity(rawEntity, entityType, false);
                                var keyMapping = { entityTypeName: entityType.name, tempValue: tempValue, realValue: realKey.values[0] };
                                keyMappings.push(keyMapping);
                            }
                        }
                        entities.push(rawEntity);
                    } else {
                        var origEntity = contentKeys[contentId];
                        entities.push(origEntity);
                    }
                });
            });
            return deferred.resolve(saveResult);
        }, function (err) {
            return deferred.reject(createError(err, url));
        }, OData.batchHandler);

        return deferred.promise;

    };
 
    ctor.prototype.jsonResultsAdapter = new JsonResultsAdapter({
        name: "OData_default",

        visitNode: function (node, mappingContext, nodeContext) {
            var result = {};
            if (node == null) return result;
            if (node.__metadata != null) {
                // TODO: may be able to make this more efficient by caching of the previous value.
                var entityTypeName = MetadataStore.normalizeTypeName(node.__metadata.type);
                var et = entityTypeName && mappingContext.entityManager.metadataStore.getEntityType(entityTypeName, true);
                if (et && et._mappedPropertiesCount === Object.keys(node).length - 1) {
                    result.entityType = et;
                    result.extra = node.__metadata;
                }
            }

            var propertyName = nodeContext.propertyName;
            result.ignore = node.__deferred != null || propertyName === "__metadata" ||
                // EntityKey properties can be produced by EDMX models
                (propertyName === "EntityKey" && node.$type && core.stringStartsWith(node.$type, "System.Data"));
            return result;
        }
        
    });

    function createChangeRequests(saveContext, saveBundle) {
        var linksRequest = [];
        var changeRequests = [];
        var tempKeys = [];
        var contentKeys = [];
        var prefix = saveContext.dataService.serviceName;
        var entityManager = saveContext.entityManager;
        var helper = entityManager.helper;
        var id = 0;
        saveBundle.entities.forEach(function (entity) {
            var aspect = entity.entityAspect;
            id = id + 1; // we are deliberately skipping id=0 because Content-ID = 0 seems to be ignored.
            var request = { headers: { "Content-ID": id, "DataServiceVersion": "2.0" } };
            contentKeys[id] = entity;

            var getId = function (entity) {
                var prefix = "", sufix = "";
                if (entity.entityType.keyProperties[0].dataType.name == "Guid") {
                    prefix = "guid'";
                    sufix = "'";
                }
                return prefix + entity.entityAspect.getKey().values[0] + sufix;
            };

            if (entity.entityAspect.entityState.isModified()) {
                aspect.inseredLinks.forEach(function (inseredLink) {
                    if (!inseredLink.entity.entityAspect.entityState.isAdded()
                        && !inseredLink.entity.entityAspect.entityState.isDeleted()) {
                        var linkRequest = { headers: { "Content-ID": id, "DataServiceVersion": "3.0" } };
                        // POST /OData/OData.svc/Categories(1)/$links/Products
                        linkRequest.requestUri = prefix + entity.entityType.defaultResourceName + "(" + getId(entity) + ")"
                            + "/$links/" + inseredLink.np.name;
                        linkRequest.method = "POST";

                        linkRequest.data = {
                            uri: prefix + inseredLink.entity.entityType.defaultResourceName
                                + "(" + getId(inseredLink.entity) + ")"
                        };

                        linksRequest.push(linkRequest);
                    }
                });

                aspect.removedLinks.forEach(function (removedLink) {
                    if (!removedLink.entity.entityAspect.entityState.isAdded()
                        && !removedLink.entity.entityAspect.entityState.isDeleted()) {
                        var linkRequest = { headers: { "Content-ID": id, "DataServiceVersion": "3.0" } };
                        // DELETE /OData/OData.svc/Categories(1)/$links/Products(10)
                        linkRequest.requestUri = prefix + entity.entityType.defaultResourceName + "(" + getId(entity) + ")"
                            + "/$links/" + removedLink.np.name + "(" + getId(removedLink.entity) + ")";
                        linkRequest.method = "DELETE";
                        linksRequest.push(linkRequest);
                    }
                });
            }

            if (aspect.entityState.isAdded()) {
                insertRequest(request, entity.entityType);
                request.method = "POST";
                request.data = helper.unwrapInstance(entity, true);
                tempKeys[id] = aspect.getKey();
            } else if (aspect.entityState.isModified()) {
                updateDeleteMergeRequest(request, aspect, prefix);
                request.method = "MERGE";
                request.data = helper.unwrapChangedValues(entity, entityManager.metadataStore, true);
                // should be a PATCH/MERGE
                if (Object.keys(request.data).length == 0) {
                    id--;
                    return;
                }
            } else if (aspect.entityState.isDeleted()) {
                updateDeleteMergeRequest(request, aspect, prefix);
                request.method = "DELETE";
            } else {
                return;
            }
            changeRequests.push(request);
        });

        linksRequest.forEach(function (link) {
            link.headers["Content-ID"] = ++id;
            changeRequests.push(link);
        });

        saveContext.contentKeys = contentKeys;
        saveContext.tempKeys = tempKeys;
        return {
            __batchRequests: [{
                __changeRequests: changeRequests
            }]
        };

    }

    function insertRequest(request, entityType) {
        var lastBaseType = null;
        var sbaseType = entityType;
        var defaultResourceName = entityType.defaultResourceName;
        do {
            lastBaseType = sbaseType;
            sbaseType = sbaseType.baseEntityType;
        } while (sbaseType);

        if (lastBaseType !== entityType) {
            var namespace = entityType.namespace;
            var className = entityType.name.replace(":#" + namespace, "");
            defaultResourceName = lastBaseType.defaultResourceName + "/" + namespace + "." + className;
        }

        request.requestUri = defaultResourceName;
    }

    function updateDeleteMergeRequest(request, aspect, prefix) {
        var extraMetadata = aspect.extraMetadata;
        var uri = extraMetadata.uri;
        if (__stringStartsWith(uri, prefix)) {
            uri = uri.substring(prefix.length);
        }
        request.requestUri = uri;
        if (extraMetadata.etag) {
            request.headers["If-Match"] = extraMetadata.etag;
        }
    }
   
    function createError(error, url) {
        // OData errors can have the message buried very deeply - and nonobviously
        // this code is tricky so be careful changing the response.body parsing.
        var result = new Error();
        var response = error.response;
        result.message = response.statusText;
        result.statusText = response.statusText;
        result.status = response.statusCode;
        // non std
        if (url) result.url = url;
        result.body = response.body;
        if (response.body) {
            var nextErr;
            try {
                var err = JSON.parse(response.body);
                result.body = err;
                var msg = "";
                do {
                    nextErr = err.error || err.innererror;
                    if (!nextErr) msg = msg + getMessage(err);
                    nextErr = nextErr || err.internalexception;
                    err = nextErr || err;
                } while (nextErr);
                if (msg.length > 0) {
                    result.message = msg;
                }
            } catch (e) {

            }
        }
        return result;
    }

    function getMessage(error) {
        var msg = error.message;
        return (msg == null) ? "" : ((typeof (msg) === "string") ? msg : msg.value) + "; ";
    }

    breeze.config.registerAdapter("dataService", ctor);

}));

